[project]
name = "berrypad"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "markdown>=3.8.2",
    "pypubsub>=4.0.3",
    "tkinterweb>=4.4.4",
]
